#!/bin/bash
# The logic to stop your application should be put in this script.
#kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
#exit 0

#kill `cat $OPENSHIFT_TMP_DIR/uwsgi.pid`
#exit 0

pkill -9 uwsgi
kill `pgrep python`
#exit 0

#kill nginx
pkill nginx
exit 0
